### ISSUE TITLE
grey halos on safari

### ISSUE THREAD

**Issue by robsmithwashere** [the-pudding/sesame#101]
When i went to safari to see whether the "handful of boxes" were highlighting, I noticed these grey halos, let's call them (see images), that pop up above characters when the avatars are performing certain kinds of motion (though not exclusively).  I think i have screen caps of all of them below. 

Chronologically, it's when:
-  michelle waves at the intro
- from the moment russell exits the hospital through to the time he walks off screen (before meeting the Dr.)
- when michelle has a speech bubble 
- when the water cooler has only 2 air bubbles (it cycles on and off depending on bubble count)
- when russell has a speech bubble
- when goggles are donned

<img width="176" alt="Screen Shot 2021-12-08 at 4 14 29 PM" src="https://user-images.githubusercontent.com/88445968/145285351-3e7dd83e-efb5-4459-bcc0-dbc33ae8b600.png">

<img width="120" alt="Screen Shot 2021-12-08 at 4 15 09 PM" src="https://user-images.githubusercontent.com/88445968/145285467-31072904-5f6c-4255-b0c1-4b54e55923c1.png">

<img width="253" alt="Screen Shot 2021-12-08 at 4 18 50 PM" src="https://user-images.githubusercontent.com/88445968/145286019-7df5e02a-52e2-42b7-bb5f-d640fb661e4e.png">

<img width="145" alt="Screen Shot 2021-12-08 at 4 20 08 PM" src="https://user-images.githubusercontent.com/88445968/145286126-7799f300-876e-4e14-bdb8-ff52bf236d06.png">

<img width="343" alt="Screen Shot 2021-12-08 at 4 21 04 PM" src="https://user-images.githubusercontent.com/88445968/145286332-bd9034d4-ce04-4d03-8ec8-35ac069cc69f.png">

**Comment by russellsamora** [comment]
@robsmithwashere what version of safari? Also if you could test again, I just pushed latest code so want to make sure it is still there.

**Comment by robsmithwashere** [comment]
Version 15.1 (17612.2.9.1.20)


*Rob Smith*Managing Director
*The Pudding* <https://pudding.cool/>
