### ISSUE TITLE
mobile + browser testing

### ISSUE THREAD

**Issue by mmcghee18** [the-pudding/sesame#73]
* [x] chrome
* [x] firefox
* [x] safari
* [ ] mobile safari
* [ ] mobile chrome

**Comment by robsmithwashere** [comment]
On the screens with a lot of text, (first seen in the chalkboard moments) I'm unable to read lines 4 onward.  Have to switch to full screen as there's  (Chrome, most up to date version -- "Version 96.0.4664.55").  Works fine in Safari though. 
<img width="1415" alt="Screen Shot 2021-12-06 at 3 20 10 PM" src="https://user-images.githubusercontent.com/88445968/144916476-cc6c1726-b250-4326-828f-f49ff7a2602d.png">
